# Supabase Configuration for Claude Code Observatory
# This file configures the local Supabase development environment
# Official Supabase CLI configuration format

project_id = "znznsjgqbnljgpffalwi"

[api]
enabled = true
port = 54321
schemas = ["public", "auth", "storage", "realtime"]
extra_search_path = ["public", "auth"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:5173", "http://localhost:8000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
enable_signup = true

[auth.external.github]
enabled = false

[auth.external.google]
enabled = false

[db]
port = 54322
major_version = 15

[db.pooler]
enabled = false
port = 54329
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true

[storage]
enabled = true
file_size_limit = "50MiB"
image_transformation = { enabled = true }

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[analytics]
enabled = false